from __future__ import annotations

import json
import urllib.error
import urllib.request
from typing import Any, Protocol

from .config import LLMConfig


class LLMClient(Protocol):
    def generate_json(self, *, system_prompt: str, user_payload: dict[str, Any]) -> dict[str, Any]:
        """Return a JSON object generated by an LLM."""


class OpenAICompatibleClient:
    def __init__(self, config: LLMConfig | None = None, timeout: int | None = None):
        self.config = config or LLMConfig.from_env()
        self.timeout = timeout if timeout is not None else self.config.timeout

    def generate_json(self, *, system_prompt: str, user_payload: dict[str, Any]) -> dict[str, Any]:
        if not self.config.api_key:
            raise ValueError("缺少 DASHSCOPE_API_KEY，无法调用大模型。")

        endpoint = self.config.base_url.rstrip("/") + "/chat/completions"
        body = {
            "model": self.config.model_name,
            "messages": [
                {"role": "system", "content": system_prompt},
                {
                    "role": "user",
                    "content": json.dumps(user_payload, ensure_ascii=False),
                },
            ],
            "response_format": {"type": "json_object"},
        }
        body.update(self.config.chat_body_options())
        request = urllib.request.Request(
            endpoint,
            data=json.dumps(body, ensure_ascii=False).encode("utf-8"),
            headers={
                "Authorization": f"Bearer {self.config.api_key}",
                "Content-Type": "application/json",
            },
            method="POST",
        )
        try:
            with urllib.request.urlopen(request, timeout=self.timeout) as response:
                payload = json.loads(response.read().decode("utf-8"))
        except TimeoutError as exc:
            raise ValueError(f"大模型请求超时：{self.timeout} 秒。") from exc
        except urllib.error.URLError as exc:
            raise ValueError(f"大模型请求失败：{exc}") from exc

        content = payload["choices"][0]["message"]["content"]
        if isinstance(content, dict):
            return content
        return json.loads(content)
